import type { Metadata } from "next";
import "./globals.css";
import { ThemesProvider } from './hooks/useTheme'; // Import your ThemesProvider


export const metadata: Metadata = {
  title: "Anton Paar Case Study",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  
  return (
    <html lang="en">
          <ThemesProvider >
      <body>{children}</body>
      </ThemesProvider>
    </html>
  );
}
